server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2
  h2:
    console:
      enabled: true
  datasource:
    url: ${h2DatasourceURL}
    username: ${springDatasourceUsername}
    password: ${springDatasourcePassword}
    driver-class-name: org.h2.Driver
      
      
logging:
  level:
    com:
      skillstorm:
        spyglass: debug
    org:
      springframework:
        web: debug
        security: debug