server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${springDatasourceURL}
    username: ${springDatasourceUsername}
    password: ${springDatasourcePassword}
  sql:
    init:
      platform: h2
logging:
  level:
    com:
      skillstorm:
        spyglass: debug
    org:
      springframework:
        web: debug
        security: debug